# Generated by Django 3.1.7 on 2021-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('snsimage', models.ImageField(upload_to='')),
                ('good', models.IntegerField(blank=True, default=0, null=True)),
                ('read', models.IntegerField(blank=True, default=0, null=True)),
                ('readtext', models.TextField(blank=True, default='a', null=True)),
                ('subtitle', models.TextField(blank=True, default='a', null=True)),
                ('material', models.TextField(blank=True, default='a', null=True)),
            ],
        ),
    ]
